services:
  db-postgres:
    image: postgres:16-alpine
    container_name: auction-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - auction-network

  db-mongodb:
    image: mongo:6.0
    container_name: auction-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - auction-network

  db-redis:
    image: redis:7-alpine
    container_name: auction-redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - auction-network

  rabbitmq:
    build:
      context: ./rabbitmq
    container_name: auction-rabbitmq
    restart: always
    ports:
      - "5672:5672" # AMQP protocol
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-admin}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - auction-network
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app-service:
    build: .
    container_name: auction-app
    restart: on-failure
    depends_on:
      - db-postgres
      - db-mongodb
      - db-redis
      - rabbitmq
      - minio
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-postgres:5432/${POSTGRES_DB}
      SPRING_DATA_MONGODB_URI: mongodb://db-mongodb:27017/${MONGO_DB:-auction_logs}
      SPRING_DATA_REDIS_HOST: db-redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USER:-admin}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASS:-admin}
      S3_ENDPOINT: http://minio:9090/
    networks:
      - auction-network

  minio:
    image: quay.io/minio/aistor/minio:RELEASE.2026-03-20T23-11-32Z
    container_name: auction-minio
    restart: always
    ports:
      - "9090:9090" # API
      - "9001:9001" # Console
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
      MINIO_LICENSE: ${MINIO_LICENSE}
    volumes:
      - minio_data:/data
    command: server /data --address ":9090" --console-address ":9001"
    networks:
      - auction-network

networks:
  auction-network:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
  redis_data:
  rabbitmq_data:
  minio_data:
